### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by peterjschroeder** [larrykollar/tines#10]
make install fails with this error

install -D /usr/local/bin
install: missing destination file operand after '/usr/local/bin'
Try 'install --help' for more information.
Makefile:23: recipe for target 'install' failed
make: *** [install] Error 1

This is on Debian Sid, gcc 7.2.0

**Comment by larrykollar** [comment]
Workaround: change the first four lines under `install:` to read:

    install $(INSTFLAGS) -d $(BINDIR)
    install $(INSTFLAGS) -d $(SHAREDIR)
    install $(INSTFLAGS) -d $(MANDIR)/man1
    install $(INSTFLAGS) -d $(MANDIR)/man7

Of course, that will break on non-Linux installs. I have a patch that should make all this faffing around unnecessary, and will post it to the dev branch after I finish testing.

**Comment by peterjschroeder** [comment]
Thank you.

**Comment by larrykollar** [comment]
Just pushed an update that should fix this, and make it unnecessary to fiddle with the Makefile further. Please test!

**Comment by peterjschroeder** [comment]
It still fails. It looks like the capital D is for non-cygwin windows only and everything else uses the lowercase d? If so something like this works.

ifeq ($(OS),Windows_NT)
        INSTFLAGS=-D
else
        INSTFLAGS=-d
endif

**Comment by aThorp96** [comment]
I just ran into this issue as well. In the Makefile's documentation it claims Linux needs `-D` while BSD and MacOS need `-d`. However I've checked Manjaro and Ubuntu and the `install` implimentation needs the `-d` flag for the use `make` wants.
